# POST https://evening-castle-33015-33fd40ba3c3e.herokuapp.com/api/notes
POST http://localhost:4001/api/notes
Content-Type: application/json

{
    "content": "Esto es una nueva nota con usuario y #######",
    "important": true,
    "userId": "652e5d0f46b50130df41dc3d"
}
#
###

#this is a missing keys body
POST http://localhost:4001/api/notes
Content-Type: application/json

{
    "important": false
}

###
#this is a malformed json for express (the trailing comma ,)
POST http://localhost:4001/api/notes
Content-Type: application/json

{
    "content": "Esto es una nueva nota con usuario y #######",
    "important": true,
}