POST http://localhost:4001/api/notes
Content-Type: application/json

{
    "content": "Esto es una nueva nota",
    "important": false

}

###

POST http://localhost:4001/api/notes
Content-Type: application/json

{
    "important": false
}
