POST http://localhost:4001/api/login
# POST https://evening-castle-33015-33fd40ba3c3e.herokuapp.com/api/login
Content-Type: application/json

{
    "username": "pinkpanther",
    "password": "pepe"
}


